# WARNING: will only be have an effect if NOT running via jetwick ElasticNode!
# otherwise jetwick's log4j comes into the game

rootLogger: INFO, console, file
logger:
  # log action execution errors for easier debugging
  action: TRACE
  #action.search: TRACE
  # reduce the logging for aws, too much is logged under the default INFO
  com.amazonaws: WARN

  # does not work to see indexing activity
  #index.engine: INFO

  # gateway
  #gateway: DEBUG
  #index.gateway: DEBUG

  # peer shard recovery
  #index.shard.recovery: DEBUG

appender:
  console:
    type: console
    layout:
      type: consolePattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

  file:
    type: dailyRollingFile
    file: ${path.logs}/${cluster.name}.log
    datePattern: "'.'yyyy-MM-dd"
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
      